### ISSUE TITLE
Some kind of memory leak

### ISSUE THREAD

**Issue by klartext** [explosion-mental/mage#6]
Looking at many images by just holding the space key pressed for a while (in a directory with more than thousand images), `mage` consumes a lot of memory.
So somehow the memory is not freed after viewing an image, when looking at the next one.

**Comment by explosion-mental** [comment]
Hello
Think about two things right now:

1. that might be related to the way `mage` loads directories. I was debating whether to have this as a built in, since something like `ls | mage` could be faster and much more cleaner..
 
2. Imlib2: there is a cache size for viewing images, hence the 'consuming memory'. It should be default to 4MB tho.

Since the plan is to have a thumbnail view (and probably custom arrangements) the cache is gonna be handy. My head broke trying to think a better way of handling images, since currently I use the sxiv/nsxiv original approach.. think maintain mode is ON!11! (no new features but I can try to fix stuff)

**Comment by explosion-mental** [comment]
Found what you meant. Thanks for reporting.


https://github.com/explosion-mental/mage/commit/e778591f2b941bed78f1fd335c6807b395e77f87
https://github.com/explosion-mental/mage/commit/d11509e130e94aade5db50e06d361a55f722d309
